spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:17324/railway
    username: postgres
    password: JgcdWOiJlXXLDFcpdyYHbwdzsdUkwbZs
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate